---
apiVersion: cluster.k8s.io/v1alpha1
kind: Machine
metadata:
  name: {{.AWS.ClusterName}}-master-{{.Index}}
  namespace: {{ .TargetNamespace }}
  labels:
    sigs.k8s.io/cluster-api-cluster: {{.AWS.ClusterName}}
    sigs.k8s.io/cluster-api-machine-role: master
    sigs.k8s.io/cluster-api-machine-type: master
spec:
  providerConfig:
    value:
      apiVersion: aws.cluster.k8s.io/v1alpha1
      kind: AWSMachineProviderConfig
      {{- if .AWS.WithCreds }}
      credentialsSecret:
        name: aws-credentials-secret
      {{- end}}
      ami:
        id: {{.AWS.Image}}
        filters:
          - name: "name"
            values:
            - CoreOS-{{.AWS.ReleaseChannel}}-{{.AWS.ContainerLinuxVersion}}-*
          - name: "architecture"
            values:
            - "x86_64"
          - name: "virtualization-type"
            values:
            - "hvm"
          - name: "owner-id"
            values:
            - "595879546273"
      instanceType: t2.medium
      placement:
        region: {{.AWS.Region}}
        availabilityZone: {{index .AWS.MasterAvailabilityZones .Index }}
      subnet:
        filters:
        - name: "tag:Name"
          values:
          - "{{.AWS.ClusterName}}-master-{{ index .AWS.MasterAvailabilityZones .Index }}"
      iamInstanceProfile:
        id: "{{.AWS.ClusterName}}-master-profile"
      tags:
        - name: tectonicClusterID
          value: {{.AWS.ClusterID}}
      securityGroups:
        - filters:
          - name: "tag:Name"
            values:
            - "{{.AWS.ClusterName}}_master_sg"
      userDataSecret:
        name: "ignition-master-{{.Index}}"
  versions:
    kubelet: ""
    controlPlane: ""
